version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'webavance_db'
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
